### PR TITLE
URI encoding of scopes, request type, and adding nonce

### PR DESCRIPTION
**Pull request by meschbach**
I'm attempting to support an OpenID Connect 1.0 system using oauth-ng.  Given the UI requirements for displaying user profile information, the project can't use the oauth directive so we are using the associated components manually; so this doesn't include modifications to the tag itself.  I would be happy to add these if you feel like they provide enough value.

The attached patches adds support for URI encoding of the scope and request types as well as nonce on the Endpoint factory, including associated tests.  To allow for better capture of state and nonce I added the capability to override the configuration given to Endpoint#set in Endpoint#get.

### CODE REVIEW

**Comment by Condor2708** [comment]
+1

**Comment by m00s** [comment]
Hi @meschbach, thank you for the contribution. We discussed about and we think to merge it soon. Could you please fix conflicts and then update the doc in the `gh-pages` branch?

**Comment by meschbach** [comment]
Hey @m00s !  I've resolved the merge conflict (the dist file was the only issue).

I browsing through the _gh-pages_ I couldn't find any documentation on the _Endpoint_ factory.  Would you like me to add details regarding this component?  I can't figure out how to add the _gh-pages_ branch to this PR, so I'll add a new one.

**Comment by m00s** [comment]
Yes you have to submit a new PR and yes if you can add some details about the Endpoint service and the new OpenID support would be awesome.
Thank you a lot

**Pull request merged**
